services:

    docs:
        image: jekyll/jekyll:3.8.5
        ports:
            - 4000:4000
        volumes:
            - ./docs:/srv/jekyll
        command: jekyll serve --incremental

    fontforge:
        image: fontforge-alpine
        volumes:
            - .:/opt/fontdev
        build:
            dockerfile: Dockerfile
