#!/usr/bin/env bash

set -e

FONTS=$(find . -type f -name *.sfd | xargs)

docker compose run --rm fontforge \
    "./scripts/convert.pe --format ttf --output ttf/ $FONTS"

for FONT in $FONTS
do
    OUTPUT=$(dirname $FONT)

    docker compose run --rm fontforge \
        "./scripts/convert.pe --format ufo --output $OUTPUT/ $FONT"
done
