#!/usr/bin/env bash

set -ex

# Build fontforge docker image
docker compose build

# Build Ome Bhatkhande fonts for each language
for LANG in hindi english punjabi
do
    docker compose run --rm fontforge \
        "/bin/sh" "-c" \
        "cd bhatkhande && \
            ./build.py $LANG && \
        cd .. && \
        ./scripts/convert.py \
            --format ttf \
            --output ttf/ \
            bhatkhande/$LANG/OmeBhatkhande*.sfd && \
        ./scripts/convert.py \
            --format ufo \
            --output bhatkhande/$LANG/ \
            bhatkhande/$LANG/OmeBhatkhande*.sfd && \
        rm bhatkhande/$LANG/OmeBhatkhande*.sfd"
done

# Build Ome Swarlipi font
docker compose run --rm fontforge \
    "/bin/sh" "-c" \
    "./scripts/convert.py \
        --format ttf \
        --output ttf/ \
        swarlipi/OmeSwarlipi.sfd && \
    ./scripts/convert.py \
        --format ufo \
        --output swarlipi/ \
        swarlipi/OmeSwarlipi.sfd"
